### ISSUE TITLE
CLJS introduction documentation.

### ISSUE THREAD

**Issue by VikramShawFL** [224-1/xtnt-micro#11]

**Comment by sahabaishakhi** [comment]
@VikramShawFL what information about cljs would you need from this that helps you? should I give directions for future figwheel implementation or about other plug-ins like cljs-build that we discussed earlier?

**Comment by VikramShawFL** [comment]
Figwheel implementation and all is issue number #12. Basically in this what I need is the implementation of clojurescript in clojure project like using of cljsbuild plugin and few codes how to write clojurescript codes.

**Comment by azureus89** [comment]
@VikramShawFL need to include figwheel and build instructions here, its part of introduction. She is asking about documentation. #12 is for implementation / porting of cljs libraries into existing xtnt-micro framework. Yes, if you want you can see the documentation for figwheel etc as part of that, thats also true, so ill leave it to you. Without fixing #12 you cant do any clojurescript, unless youre trying to do it in a separate project. Is that the case?

**Comment by VikramShawFL** [comment]
No that is not the case. I thought that by the time figwheel implementation documentation will be ready I can use cljsbuild plugin and close the issue. Nevermind, make the documentation for both figwheel and cljsbuild plugin and also how to convert javascript code to clojurescript

**Comment by azureus89** [comment]
@sahabaishakhi basically focus on the main clojurescript documentation here first, on priority... so that vikram can get moving with the clojurescript work. On the project that he is working on his solution doesnt need figwheel in order to close the issue, so you can focus on that next. Is that correct vikram?

**Comment by VikramShawFL** [comment]
Yes

**Comment by sahabaishakhi** [comment]
@VikramShawFL I created a standard project.clj file which contains the appropriate key attributes to use the cljs-build plugin.. the other option apart from figwheel is the use of shadow-clj plugin but I did not use that because it needed me to install npm. let me know what else I can include in the documentation..

**Comment by VikramShawFL** [comment]
@sahabaishakhi Are you sure that is working because you haven't added the clojurescript dependency and in order to run clojurescript file just we need to add all this in our ``project.clj`` right. For the first time user do we need to add anything in ``Dot Spacemacs File`` or installing anything. 
Add the ClojureScript documentation also.

**Comment by sahabaishakhi** [comment]
@VikramShawFL I did not compile anything yet. I believe this issue was only about documentation and the basics of the plug in that is to help you. Do you want me to compile and show you an output? the documentation would be easier if I show the appropriate code, so I added them in project.clj file. I had searched yesterday for clojurescript dependencies inside dot spacemacs file but we hadn't added them..

**Comment by azureus89** [comment]
@VikramShawFL can you please state very clearly what you need @sahabaishakhi to help you with right now.

@sahabaishakhi please avoid confusing people with things like shadow-clj plugin etc ... your job is to simplify, not explain nuances at the moment. Please make sure you understand from vikram EXACTLY what he needs you to document on the project.

**Comment by azureus89** [comment]
@sahabaishakhi @VikramShawFL what is going wrong here, why is this issue not moving towards closing?

**Comment by VikramShawFL** [comment]
@sahabaishakhi had explained the cljsbuild plugin we are good to close this issue. Right now she is making documentation for Figwheel.

**Comment by azureus89** [comment]
@VikramShawFL how are we good to close this issue ... I dont see any clojurescript documentation.
I would like you to list out here what all you need from a documentation point of view, in points.
@sahabaishakhi issue gets closed when these are done. I may add some requirements from my side as well, in case vikram is missing anything.

**Comment by VikramShawFL** [comment]
As mentioned above
1) In order to run CLJS what we need to add in project.clg(like figwheel) and a brief explanation why we are adding?
2) What we need to run in repl or in shell?
3) Some examples to write CLJS code.

**Comment by azureus89** [comment]
@VikramShawFL @sahabaishakhi who is working on this ... and why is there no output for a simple introduction to clojurescript that people can follow as yet?

**Comment by VikramShawFL** [comment]
> As mentioned above
> 
> 1. In order to run CLJS what we need to add in project.clg(like figwheel) and a brief explanation why we are adding?
> 2. What we need to run in repl or in shell?
> 3. Some examples to write CLJS code.

Have already cover the first two points in the documentation for adding cljs, figwheel-main to existing project. @sahabaishakhi will do the point number 3 as she has worked more than me on cljs.

**Comment by azureus89** [comment]
cool.
Think issue is work is very unorganised. This is issue #11 .. 
points 1 and 2 should have been moved to #16 
the documentation for that should have been pushed in a new branch vk-16, instead of in vk-4 .... if doing in vk-4 itself, it should be mentioned in the issue thread and pull request, that you are combining the issues, so that work and discussions are not spread across ...

Whatever is pertinent to this issue will be solved in documentation submitted under vk-11

make sure all your branches and discussions are organised like this now ... because you and @sahabaishakhi have allowed the issue discussion and resolution to spread between various issue threads and branches
