### ISSUE TITLE
Unhandled java.net.BindException Address already in use

### ISSUE THREAD

**Issue by VikramShawFL** [224-1/xtnt-micro#23]
I was going through the issue where you had explained about how to run the websocket which has clj and cljs in it.
I understood that we need ``cider-jack-in`` to load the program and if there is any changes in the routing configuration, otherwise we only need ``lein run`` to run the websocket.  ``cider-jack-in-cljs`` to compile the cljs code to javascript and to run the auto update.
Correct me if I'm wrong as far as I understood the error I'm getting is because ``lein run`` is running on port 9500 and figwheel-main default port is also 9500 which I'm running through ``cider-jack-in-cljs``.

**Comment by azureus89** [comment]
Change the ports so there is no conflict .. anyway you are hardcoding the ports for now .. either change http-kit server port or the figwheel main port

**Comment by VikramShawFL** [comment]
Changing the http kit port in `` (hk/run-server app {:port 9500})`` is breaking the code. I even tried `` :connect-url "ws://localhost:8000/figwheel-connect"``  by adding in figwheel.main . Maybe I am doing wrong something. 
How to change the port number of figwheel main port?
I have changed `` (hk/run-server app {:port 9500})`` to ``(hk/run-server app {:port (Integer. port)})`` so that I can run serve on any port using lein run ''port-number''  but again the websocket is only working on port 9500 and having the same conflict issue.
How to solve this? Any suggestion

**Comment by azureus89** [comment]
I'm not having any issues when I change the port to 8000.
Same has to reflect in the core.cljs file too in the ws url ... pushing commit and merging to master.

You don't need to do anything else, it works fine.
If you're running both repls then .. 
a) start the clojure repl
in the repl run (-main)
open localhost:8000 and see if its loading
note: this will still give you a websocket error because you've not yet run the cljs repl so it hasnt yet compiled the changes in core.cljs - so its still running on the old javascript file that is trying to find the websocket port on ws://localhost:9500/ws

b) run the clojurescript repl
if it asks if you want to run as sibling, say yes
choose figwheel-main
:dev profile
go to the repl window
it will show you what is happening, errors etc
it should compile with no errors, and open the figwheel live loading page on localhost:9500


the normal page (not live loading) will still work on localhost:8000 ... but you will have to keep reloading manually, some times you have to refresh cache etc for the changes to show.

because the websocket server is the same, you should be able to connect between the two pages also.

any issues, you'll see it in the chrome/firefox console

pushing commits now and merging into master .. ill be closing this issue once you have verified that its working on your end also

**Comment by VikramShawFL** [comment]
That's what it was confusing me, how to run both the repl and also the server.
Yes it is working fine. we can close the issue.

**Comment by azureus89** [comment]
closing the issue, include the instructions in documentation, so other people dont run into the same problem
